### ISSUE TITLE
Test Traefik 2.9+

### ISSUE THREAD

**Issue by torbsto** [bakdata/quick#149]
We have the requirement that Quick should work with the newest version of Traefik, which currently is [2.9.5](https://github.com/traefik/traefik/releases/tag/v2.9.5). This should be tested.

**Comment by raminqaf** [comment]
@torbsto I have destroyed the old traefik and deployed the newest version and ran the e2e tests of Quick and it seems to me that all the requests arrive to the cluster and everything works as expected. So closing this issue.
