### ISSUE TITLE
Document supported GraphQL elements

### ISSUE THREAD

**Issue by raminqaf** [bakdata/quick#32]
We should consider adding a section in our documentation where we address the supported GraphQL elements. For example, we are not supporting GraphQL Schemas with _Union_ or _Interface_ types.

**Comment by DawidNiezgodka** [comment]
Maybe something along these lines:

Currently, Quick supports the following GraphQL types:
1. The mandatory `Query` type and the optional `Mutation` type,
2. Basic Types with field declarations as well as type modifiers, for example: `Type Character {name:String!, appearsIn:[Episode!]}`,
3. All scalar types: `Int`, `String`, `Float`, `Boolean`, `ID` together with field's arguments, for example: `total(moreThan: Int = 50): Float`,
4. Enumerations,
5. Inputs.

Thus, the following types are **not** supported:
1. Interfaces,
2. Unions,
3. Custom scalars, for example: `scalar MyCustomScalar`.
