### ISSUE TITLE
Investigate high latency ingestion

### ISSUE THREAD

**Issue by raminqaf** [bakdata/quick#54]
After [upgrading Kafka to 3.1](https://github.com/bakdata/quick/pull/53), the ingestion time increased noticeably. I had to add sleeps in the e2e tests after each ingest. We should investigate what the main reason is.

**Comment by DawidNiezgodka** [comment]
[Results](https://docs.google.com/spreadsheets/d/1WHHjAwdMIJfZPNO5R30b7vuMv1A2bpOo42XS1je8t-Y/edit#gid=0)

**Comment by DawidNiezgodka** [comment]
The second part of the test involves testing the _consumption time_, that is, we want to measure how much time a consumer needs to read all records send by the ingest service to a specific kafka topic.

**Comment by DawidNiezgodka** [comment]
[Results with the consumer time](https://docs.google.com/spreadsheets/d/16Z3XJlex6agtvhjZcLQrPggZPeZ_uIOH3ry5mD9v-cI/edit#gid=0)

**Comment by DawidNiezgodka** [comment]
Hypothesis: Kafka 3 needs more time for the stuff around producer and consumer (de)activation. When they are already active, then the processing is faster than Kafka 2. One of the solution to the problem could be to add additional resources to speed up the start-up.
